hyperparameters:
  dm: 0
  vector_size: 50
  window: 5
  min_count: 2
  epochs: 50
  common_params:
    negative: 5
    hs: 0
    sample: 0
    seed: 0
  random_split: True
  stratify: True
  scale: False
  dataset:
    name: EU_judgements