hyperparameters:
  num_hidden1: 2048
  num_hidden2: 1024
  num_hidden3: 512
  dropout_p: 0.3
  lr: 0.0001
  batch_size: 500
  epochs: 40
  dataset:
    name: EU_judgements
    stratify: False
    random_split: True
    scale: False