hyperparameters:
  num_hidden1: 1024
  num_hidden2: 512
  num_hidden3: 256
  dropout_p: 0.2
  lr: 0.0001
  batch_size: 500
  epochs: 40
  scale: False
  dataset:
    name: ogbn-arxiv
    stratify: False
    random_split: True