hyperparameters:
  num_hidden1: 512
  num_hidden2: 512
  num_hidden3: 258
  dropout_p: 0.3
  lr: 0.01
  batch_size: 1000
  epochs: 20
  scale: False
dataset:
  name: ogbn-arxiv
  stratify: False
  random_split: True