hyperparameters:
  num_hidden1: 2048
  num_hidden2: 1024
  num_hidden3: 512
  dropout_p: 0.2
  lr: 0.001
  batch_size: 1500
  epochs: 40
  inference: True
  dataset:
    name: ogbn-products
    stratify: False
    random_split: True
    scale: False