hyperparameters:
  num_hidden1: 2048
  num_hidden2: 1024
  num_hidden3: 512
  dropout_p: 0.4
  lr: 0.001
  batch_size: 200
  epochs: 40
  dataset:
    name: ogbn-products
    stratify: False
    random_split: False
    scale: False