hyperparameters:
  hidden_channels: 50
  dropout_p: 0.1
  epochs: 200
  lr: 0.01
  scheduler_step_size: 100
  scheduler_gamma: 0.1
  num_bases: 10
  heads: 1
  dataset:
    name: EU_judgements
    random_split: True
    scale: False