hyperparameters:
  hidden_channels: 128
  dropout_p: 0.2
  epochs: 100
  lr: 0.01
  scheduler_step_size: 100
  scheduler_gamma: 0.1
  num_bases: 30
  num_layers: 3
  heads: 1
  batch_size: 512
  mini_batch: False
  inductive: False
  model: gcn
  aggr: mean
  linear: True
  inference: False
  dataset:
    name: EU_judgements
    random_split: True
    scale: False