hyperparameters:
  hidden_channels: 256
  dropout_p: 0.2
  epochs: 2
  lr: 0.01
  scheduler_step_size: 70
  scheduler_gamma: 0.1
  num_bases: 30
  num_layers: 4
  heads: 1
  batch_size: 258
  mini_batch: False
  inductive: True
  model: gcn
  aggr: mean
  linear: False
  inference: True
  dataset:
    name: EU_judgements
    random_split: True
    scale: False