hyperparameters:
  C_range: 100 #[0.01,0.1,10,100,1000]
  max_iter: 5000
  random_state: 0
  scale: True
  inference: True
  dataset:
    name: ogbn-products
    random_split: True
    stratify: False