program: ./src/models/paragraph_embeddings.py
method: bayes
entity: thekatin
project: master-thesis
metric:
  goal: maximize
  name: valid_score
parameters:
  doc2vec.hyperparameters.dm:
    values: [0, 1]
  doc2vec.hyperparameters.vector_size:
    values: [10, 20, 30, 40, 50]
  doc2vec.hyperparameters.window:
    values: [2, 3, 5, 6]
  doc2vec.hyperparameters.min_count:
    values: [1, 2, 3, 5]
  doc2vec.hyperparameters.epochs:
    values: [30, 40]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
