program: ./src/models/ml_classifiers/train_model3.py
method: bayes
entity: thekatin
project: master-thesis
metric:
  goal: maximize
  name: valid_score
parameters:
  ffnn.hyperparameters.num_hidden1:
    values: [1024, 1500, 2048]
  ffnn.hyperparameters.num_hidden2:
    values: [512, 1024]
  ffnn.hyperparameters.num_hidden2:
    value: 512
  ffnn.hyperparameters.lr:
    values: [0.0001, 0.001, 0.01, 0.1]
  ffnn.hyperparameters.dropout_p:
    values: [0, 0.1, 0.2, 0.3, 0.4]
  ffnn.hyperparameters.batch_size:
    values: [200, 500, 1000, 1500]
  ffnn.hyperparameters.dataset.name:
    value: ogbn-products
  ffnn.hyperparameters.dataset.random_split:
    value: False
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
