hyperparameters:
  eta: 0.1
  learning_rate: 0.1
  min_child_weight: 1
  subsample: 0.5
  max_depth: 20
  gamma: 0.2
  num_round: 100
  colsample_bytree: 1
  objective: multi:softmax
  tree_method: hist
  scale: False
  dataset:
    name: EU_judgements
    stratify: False
    random_split: True