hyperparameters:
  embedding_dim: 256
  walk_length: 20
  context_size: 10
  walks_per_node: 10
  num_negative_samples: 1
  p: 1.5
  q: 0.5
  batch_size: 700
  epochs: 500
  lr: 0.001
  inference: True
  dataset:
    name: ogbn-products
    random_split: True
    stratify: False 